// GENERATED by `flutterfire configure` — project: momstime-app
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQXSVJC4DvCd5M82VGraut864-Xmv8j4',
    appId: '1:164422916379:web:c98f4bd2be0e0bcc321bbe',
    messagingSenderId: '164422916379',
    projectId: 'momstime-app',
    authDomain: 'momstime-app.firebaseapp.com',
    storageBucket: 'momstime-app.firebasestorage.app',
    measurementId: 'G-E6DSN9ZZGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD010DCkL5ivLF3leKxKwUdTFO6aSm5ypY',
    appId: '1:164422916379:android:3ada268c96a67a9d321bbe',
    messagingSenderId: '164422916379',
    projectId: 'momstime-app',
    storageBucket: 'momstime-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0vDgN9RcpdWwVPI3PqJox2xW7nT8X6O8',
    appId: '1:164422916379:ios:0f928d75eeef8da9321bbe',
    messagingSenderId: '164422916379',
    projectId: 'momstime-app',
    storageBucket: 'momstime-app.firebasestorage.app',
    iosClientId: '164422916379-voo63ughtpls8tp7us0oel275bjbes68.apps.googleusercontent.com',
    iosBundleId: 'com.momstime.momTime',
  );
  /// placeholder 값이 그대로면 true (실제 설정 전).
  static bool get isConfigured => android.apiKey != 'REPLACE_ME';
}
